Repository NCATComp410/comp410_summer_2023, pull requests merged in 2023-06, with the labels that each got.

#17 Added detection for political group
  test_pii_scan.py
Labels: Team1

#18 Added detection for phone number
  test_pii_scan.py
Labels: JKN^2

#21 Added name detection
  test_pii_scan.py
Labels: JKN^2

#20 Added detection for social security
  test_pii_scan.py
Labels: JKN^2

#24 Added Banner ID entity and Banner ID detection
  pii_scan.py
  test_pii_scan.py
Labels: JKN^2

#26 added detection for IPv4
  test_pii_scan.py
Labels: Team1

#30 Added Detection for Religious Affiliation
  test_pii_scan.py
Labels: TeamA
